name: tests

on: 
   pull_request: 
   push: 
     branches: 
       - main

jobs:
  test:
    strategy:
      matrix:
        os: [arch, artix-openrc, artix-runit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Add permissions to execute scripts
        run: chmod +x -R tests

      - name: Run docker tests
        run: ./tests/docker-test.sh ${{ matrix.os }}

