name: test

on: 
   pull_request: 
   push: 
     branches: 
       - main

jobs:
  test:
    strategy:
      matrix:
        os: [arch, artix-openrc, artix-runit]
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: docker pull archlinux
        run: docker pull archlinux

      - name: docker pull artixlinux/openrc
        run: docker pull artixlinux/openrc

      - name: docker pull artixlinux/runit
        run: docker pull artixlinux/runit

      - uses: actions/checkout@v4

      - name: Add permissions to execute scripts
        run: chmod +x -R test

      - name: Run docker test
        run: ./test/docker-test.sh ${{ matrix.os }}

