name: test

on: 
   pull_request: 
   push: 
     branches: 
       - main

jobs:
  test:
    strategy:
      matrix:
        os: [arch, artix-openrc] #TODO: add previously removed artix-runit when artixlinux/artixlinux docker image will be fixed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Add permissions to execute scripts
        run: chmod +x -R test

      - name: Run docker test
        run: sudo ./test/docker-test.sh ${{ matrix.os }}

