name: test

on: 
   pull_request: 
   push: 
     branches: 
       - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Add permissions to execute scripts
        run: chmod +x -R scripts
      
      - name: Run docker integration_tests
        run: ./scripts/docker-test.sh

